---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        exclude_paths:
        - "src/**/*.spec.js"
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "src/**/*.js"
    - "src/**/*.jsx"
