---
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
  sourceType: module

extends: airbnb

plugins:
  - import

env:
  browser: true
  node: true

globals:
  webpack_isomorphic_tools: true
  fetch: true

rules:
  global-require: 0
  max-len: 0
  no-console: 0
  no-constant-condition: 0
  no-underscore-dangle: 0
  no-unused-vars:
  - 2
  - varsIgnorePattern: ignored
  react/prefer-stateless-function: 0
  strict: 0

settings:
  import/resolver: webpack
