language: node_js
node_js:
- '6'
os:
- linux
notifications:
  email: false
before_script:
- npm install
- npm install -g codeclimate-test-reporter
script:
- npm test
after_success:
- codeclimate-test-reporter < coverage/lcov.info
before_deploy:
- npm run build
- git add -f webpack-assets.json
env:
  global:
    secure: U5GSXDXJcaDbBT+oOw5RPp0gimdC3354eWAIFfEbwgb4OTqbENW9UEjQif7nghLmAQOJEArF+sv9D75VkOpdn7gshdUxx3IMyt5M0vex4u2RYVn0ySsSB7k1y8bnd4vFMv3Y9yyYHb87d3nwREti3XLqu0PQO/rAGKt8lxHZGvXlus2wpbHEAPlf1InAp1ANDa+eVzQ/ifcL/XW9nyv5qPgDdJ65CLCubn2FZWG9CZXIsCbgsDpPUGVlLxF3jw+Ft2O/rgo2zdLEi/NleEj/spAcWde4TNU1Nn3ycgQy8JuNqW4imZPY3mhy+bIUSB0mDLGx0MKDbijDukbxAV/K2dmtW9RM3RkK1SQcqcA/gLMyr8LpMIyRg1zpcRITtnGmRIb8KulD6SyoYSKgBC5Irhb55pFicRyQP7wVNLwBcy4O+c5EfYz5N8lBUD4FYrskHQlKD/DUWe4b2BYxWt2Qs4f4Y82F7j5/j5WQilaUWQF+JpwKHnW/yM2GvVvxZo/I7G5KXxEiGAxQ+8VxHat8SeGJxpoeJkRgMzBCAbmzeZVSLRrqoZhgJ7SAXt1S1CpY4AWtQxIhaXtfBpF7/5RZphnvJSbinfYwlERvaJkKhq6UoWVenNMWJR9sgqUTqpmODeqeNqtLnW9QJ1XY/b82cXKhO2kIkgJWUhSeP27lP14=
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAILXGJT7TZ2HIQOCQ
  secret_access_key:
    secure: CDATxM8UQQJ+1w6XC9gQvl1Q5u68FlvmfqUaKEh0bsKBkx8QKDU/ny56tvWEntMcxnntND9jxyeKgD4QpdmABLT/4sHhpaH1qMak8y8+21qTxU/rO8kBxI+B5lGXBPObwEob6azRhuID5VMEdrc3H5vwvipEQEQe3R6bq2RLTxYNX/RTeZQ/f+he1+evVQ2xNtJIHbVZoJD1DXF8FXS6Z9gOJVjSjP23nQFTM+Amwts17xuqIdrQpMZFhq/qJGZD0fGgQvOXm++d1ZtubQOehBCU6g7MQxPRo0uDbaeMBdf6gREx2vDexP1p/OlyD2za/vP80nr1KN/Ap3b+OkQlLkaNMSKWYWkQN8uMYAQ/dqDsPMtsx1SI5Eqn0eGcYkiiittszfZIjSVbAkScTGmKRBTDpD8Mu0XvbzTxx0dq0wTrS2SbkjLeZVetmxfbjSAYsFC21BbqH9Qbur6IU0AOirFZw2L3PMx9pxbKIEt5YPyXyACEAZKvmyRzMR/67KlI4p7Xnv6bqiYhm4HGQmapHbGJfG3fEuCm4KTBYPRPQgOhp3+GVctIeF+VX9KZPKVOryA2+8H/j3nuLz0SZ8OmLfl0KJWpqD9+FY2tPWR0d4H0KIZ0hGmrYEL3esSd9gMFNV/XmRaiXn1nu14yD5OPTGqq6w5a9nH4+2UHjJpqqkg=
  region: eu-west-1
  app: Monzo-Dashboard
  bucket_name: monzo-dashboard
  env: production
  on:
    branch: master
    repo: LukeSheard/Monzo-Dashboard
