language: cpp
sudo: false
env:
  - export NODE_VERSION="6"
os:
  - linux

notifications:
  email: false

before_install:
  - curl -o ~/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh # update nvm
  - bash -c "nvm use $NODE_VERSION" || true
  - bash -c "source ~/.nvm/nvm.sh; nvm install $NODE_VERSION; node --version"
# node 4 depends on gcc 4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8

before_script:
  - npm install
script:
  - npm run lint
  - npm test
