language: node_js
node_js:
  - "5"
  - "6"

env:
  global:
    secure: qXPq9f/cuXVJkN4QpaAVuXYK/MXocEur7n73jO6BLoonJnsogm7NsjSezReBLvRT49QyVoQsN/idr4tvvr5t3L0FCxjy/eW9mzedTBwWaibDlQ3FO8ZklXk5J8MCxRbAC5f5U3/ZAqvozKoqt+wli607fvpaB0N6/GCSt2JOtl9IzH8YIAx+Iy7uHp2NC8JkWbfimXyTAfP26i3yXpMDfohsukKtB0J3snvl4KKA929pEYPy93KGoKhSCvtaGOlY8rAqXXXUghYnn/DwUzaLSbyH+jNC3A5q4tEB1BX5I4+fM3FPwuTXtt/Q5dn0soTeSTWqLWsr3HlS+gvu8b4iZPWwu+axi2PRaribfP49f3zWS99Sq/Evx0vIaWFnVhxHCPTkNeRjexuVQbKYdwsqJpqY0NsYdm3h+zvN96ZGC2ezwQY6wpdAI/9al2XASiKrXF2K36czLNAQQ/0wDZGvOwiCJGffqoSdZANEAPyK5Q8D97Yz0M+YifDPYlgAiIeXynAtOlAbwVCVOGgDB88m61oxHVTWKdVpxYSj6L3sqkBwW0q9fixLKxX4Z8le3A4mBz7qu0yG/h+h7hR3GiJ78skl1mj53I/NDviwByf48P/YiiviFQ6n/bVlQCRusc3hC0LMm8tBEa4Va48O2V/E55gKGdjWb4L2J6o6tJicqDQ=
os:
- linux

notifications:
  email: false

before_script:
- npm install
- npm install -g codeclimate-test-reporter

script:
- npm test

after_script:
- codeclimate-test-reporter < coverage/lcov.info

deploy:
  provider: heroku
  app:
    master: mondo-dashboard
  on:
    branch: master
  api_key:
    secure: bxlfUhZAdu4HLOIF97mWOsZVmd+j9X21+eKTByqsGKVhgwzpQRKcJCr1SolweYWhy61udOVnNS75Jojzm54PBgtq/CNaNwyZyJLszsUcGmjrjhniu2XgUrqhq6qlhO3ouZHQzs4cGqXamXYUHf4h1p2wnL3g9/FqulesTl1HUJVMr1mTjh3FhLBXLgeiQDUw94jEd6pd+Oacnbj4AklgMqQSIl4iXT9JG4snPMORFiANVLLe8kLaJTBsZKJy0qBSEywQFHGcIW7qUnnH5vEVFdCBOmSu3/1vXrEZJMCP8Amy6PLKFA1ejUDEi1NA88lMUiDcco8L57mO0qQqSbBxYbQNk4P7GTwpk9wlEkH6hm4iNFBswWbXZxQ9sBmnd8ZfiMXwjrK4FcqBY10veuhcCXFlCMd8lz26KEl0dgb1S1vOsM9w1adhPQrQxi42Qx3OwdmyhZNj8gubypJjRWesyxqj07n7jYVlFvPrHy42aMAUpKMJUB37k3bTyg5zKfNff36DUjp9rg0VNpWYEfUQEBszjRB51ZQXwvgZ+3Vvhw3lCkKuoI0l72Pglbe6gAIb1uSfX1vIA/hILYgN/U7Cy0muiDuin/tCjkRVL7FqSMU1gN8aY1lxL/dRTAqoXNyBDaLRMiI1uQESzU8vH3GaGZ9YQ7p0eVVh6TnsQp7kZr8=
